[project]
name = "fastapi-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic~=1.13.0",
    "asyncpg~=0.29.0",
    "fastapi[standard]>=0.136.3",
    "greenlet>=3.5.1",
    "passlib[bcrypt]~=1.7.4",
    "psycopg2-binary~=2.9.0",
    "pwdlib[argon2]>=0.3.0",
    "pyjwt>=2.13.0",
    "pytest~=8.2.0",
    "pytest-asyncio~=0.23.0",
    "pytest-cov~=5.0.0",
    "python-jose[cryptography]~=3.3.0",
    "python-multipart~=0.0.9",
    "redis>=5.0.0",
    "ruff~=0.4.0",
    "sqlalchemy~=2.0.0",
]
[tool.fastapi]
entrypoint = "app.main:app"
