"""initial_schema

Revision ID: e0455cd8a8cc
Revises: 
Create Date: 2026-06-12 09:54:51.688160+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers — used by Alembic, do not edit
revision: str = 'e0455cd8a8cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('embedding_id', sa.String(length=64), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_postings_company_title', 'job_postings', ['company', 'title'], unique=False)
    op.create_index(op.f('ix_job_postings_dedup_hash'), 'job_postings', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_job_postings_embedding_id'), 'job_postings', ['embedding_id'], unique=False)
    op.create_index('ix_job_postings_status_created', 'job_postings', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_postings_url'), 'job_postings', ['url'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='True once email verification is complete.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cv_hash', sa.String(length=64), nullable=False),
    sa.Column('retrieval_query', sa.Text(), nullable=False),
    sa.Column('retrieved_posting_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_text', sa.Text(), nullable=False),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('failed_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('query_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('context_recall_score', sa.Float(), nullable=True),
    sa.Column('hallucination_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_degraded', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_results_confidence', 'analysis_results', ['confidence_score'], unique=False)
    op.create_index('ix_analysis_results_status', 'analysis_results', ['status'], unique=False)
    op.create_index('ix_analysis_results_user_created', 'analysis_results', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_user_id'), 'analysis_results', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_user_id'), table_name='analysis_results')
    op.drop_index('ix_analysis_results_user_created', table_name='analysis_results')
    op.drop_index('ix_analysis_results_status', table_name='analysis_results')
    op.drop_index('ix_analysis_results_confidence', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_job_postings_url'), table_name='job_postings')
    op.drop_index('ix_job_postings_status_created', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_embedding_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_dedup_hash'), table_name='job_postings')
    op.drop_index('ix_job_postings_company_title', table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###